version: '2'
services:
  client:
    build:
      context: ./
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
      - server
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    image: juankasantana/theam-backend
    command: /usr/app/node_modules/.bin/nodemon bin/www
    ports:
      - "5000:5000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true